### ISSUE TITLE
NullPointerException when running for the first time the stable version

### ISSUE THREAD

**Issue by anthony-o** [inspectit-docker/cmr#4]
I've run `docker run -itd --name inspectIT-CMR -p 8182:8182 -p 9070:9070 -v /var/local/inspectIT/config:/CMR/config -v /var/local/inspectIT/ci:/CMR/ci inspectit/cmr:1.6.9.83` (the **stable** version) and the container fails to start with this error log:

```
2016-10-24 09:14:30,037: 346    [           main] INFO      rocks.inspectit.server.CMR - Central Measurement Repository is starting up!
2016-10-24 09:14:30,041: 350    [           main] INFO      rocks.inspectit.server.CMR - ==============================================
2016-10-24 09:14:30,041: 350    [           main] INFO      rocks.inspectit.server.CMR - The version of this JVM (1.7.0-u80-unofficial) is compatible with the CMR.
2016-10-24 09:14:30,041: 350    [           main] INFO      rocks.inspectit.server.CMR - Initializing Spring...
2016-10-24 09:14:31,833: 2142   [           main] INFO  erver.property.PropertyManager - |-Loading the default CMR configuration
2016-10-24 09:14:31,834: 2143   [           main] INFO  erver.property.PropertyManager - |-No CMR Configuration updates found, continuing to use default configuration
2016-10-24 09:14:31,839: 2148   [           main] ERROR            java.lang.Throwable - Exception in thread "main" org.springframework.beans.factory.access.BootstrapException: Unable to initialize group definition. Group resource name [classpath*:beanRefContext.xml], factory key [ctx]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ctx' defined in URL [jar:file:/CMR/inspectit-cmr.jar!/beanRefContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.context.support.ClassPathXmlApplicationContext]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.context.support.PropertySourcesPlaceholderConfigurer#0': Cannot resolve reference to bean 'localPropertiesBean' while setting bean property 'properties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localPropertiesBean' defined in class path resource [rocks/inspectit/server/property/PropertyManager.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [protected synchronized java.util.Properties rocks.inspectit.server.property.PropertyManager.getProperties()] threw exception; nested exception is java.lang.NullPointerException
2016-10-24 09:14:31,839: 2148   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.access.SingletonBeanFactoryLocator.useBeanFactory(SingletonBeanFactoryLocator.java:386)
2016-10-24 09:14:31,839: 2148   [           main] ERROR            java.lang.Throwable -    at rocks.inspectit.server.CMR.startRepository(CMR.java:95)
2016-10-24 09:14:31,839: 2148   [           main] ERROR            java.lang.Throwable -    at rocks.inspectit.server.CMR.startCMR(CMR.java:81)
2016-10-24 09:14:31,840: 2149   [           main] ERROR            java.lang.Throwable -    at rocks.inspectit.server.CMR.main(CMR.java:240)
2016-10-24 09:14:31,840: 2149   [           main] ERROR            java.lang.Throwable - Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ctx' defined in URL [jar:file:/CMR/inspectit-cmr.jar!/beanRefContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.context.support.ClassPathXmlApplicationContext]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.context.support.PropertySourcesPlaceholderConfigurer#0': Cannot resolve reference to bean 'localPropertiesBean' while setting bean property 'properties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localPropertiesBean' defined in class path resource [rocks/inspectit/server/property/PropertyManager.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [protected synchronized java.util.Properties rocks.inspectit.server.property.PropertyManager.getProperties()] threw exception; nested exception is java.lang.NullPointerException
2016-10-24 09:14:31,840: 2149   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285)
2016-10-24 09:14:31,840: 2149   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1077)
2016-10-24 09:14:31,841: 2150   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:981)
2016-10-24 09:14:31,841: 2150   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
2016-10-24 09:14:31,841: 2150   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
2016-10-24 09:14:31,841: 2150   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
2016-10-24 09:14:31,841: 2150   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
2016-10-24 09:14:31,842: 2151   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
2016-10-24 09:14:31,842: 2151   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
2016-10-24 09:14:31,842: 2151   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
2016-10-24 09:14:31,842: 2151   [           main] ERROR            java.lang.Throwable -    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:938)
2016-10-24 09:14:31,842: 2151   [           main] ERROR            java.lang.Throwable -    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
2016-10-24 09:14:31,842: 2151   [           main] ERROR            java.lang.Throwable -    at org.springframework.context.access.ContextSingletonBeanFactoryLocator.initializeDefinition(ContextSingletonBeanFactoryLocator.java:143)
2016-10-24 09:14:31,843: 2152   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.access.SingletonBeanFactoryLocator.useBeanFactory(SingletonBeanFactoryLocator.java:381)
2016-10-24 09:14:31,843: 2152   [           main] ERROR            java.lang.Throwable -    ... 3 more
2016-10-24 09:14:31,843: 2152   [           main] ERROR            java.lang.Throwable - Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.context.support.ClassPathXmlApplicationContext]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.context.support.PropertySourcesPlaceholderConfigurer#0': Cannot resolve reference to bean 'localPropertiesBean' while setting bean property 'properties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localPropertiesBean' defined in class path resource [rocks/inspectit/server/property/PropertyManager.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [protected synchronized java.util.Properties rocks.inspectit.server.property.PropertyManager.getProperties()] threw exception; nested exception is java.lang.NullPointerException
2016-10-24 09:14:31,843: 2152   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
2016-10-24 09:14:31,843: 2152   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:121)
2016-10-24 09:14:31,844: 2153   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:277)
2016-10-24 09:14:31,844: 2153   [           main] ERROR            java.lang.Throwable -    ... 16 more
2016-10-24 09:14:31,844: 2153   [           main] ERROR            java.lang.Throwable - Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.context.support.PropertySourcesPlaceholderConfigurer#0': Cannot resolve reference to bean 'localPropertiesBean' while setting bean property 'properties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localPropertiesBean' defined in class path resource [rocks/inspectit/server/property/PropertyManager.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [protected synchronized java.util.Properties rocks.inspectit.server.property.PropertyManager.getProperties()] threw exception; nested exception is java.lang.NullPointerException
2016-10-24 09:14:31,844: 2153   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:334)
2016-10-24 09:14:31,844: 2153   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
2016-10-24 09:14:31,845: 2154   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1419)
2016-10-24 09:14:31,845: 2154   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1160)
2016-10-24 09:14:31,845: 2154   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
2016-10-24 09:14:31,845: 2154   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
2016-10-24 09:14:31,845: 2154   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
2016-10-24 09:14:31,846: 2155   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
2016-10-24 09:14:31,846: 2155   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
2016-10-24 09:14:31,846: 2155   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
2016-10-24 09:14:31,846: 2155   [           main] ERROR            java.lang.Throwable -    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:662)
2016-10-24 09:14:31,846: 2155   [           main] ERROR            java.lang.Throwable -    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461)
2016-10-24 09:14:31,846: 2155   [           main] ERROR            java.lang.Throwable -    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
2016-10-24 09:14:31,847: 2156   [           main] ERROR            java.lang.Throwable -    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
2016-10-24 09:14:31,847: 2156   [           main] ERROR            java.lang.Throwable -    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2016-10-24 09:14:31,847: 2156   [           main] ERROR            java.lang.Throwable -    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2016-10-24 09:14:31,847: 2156   [           main] ERROR            java.lang.Throwable -    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2016-10-24 09:14:31,847: 2156   [           main] ERROR            java.lang.Throwable -    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
2016-10-24 09:14:31,848: 2157   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
2016-10-24 09:14:31,848: 2157   [           main] ERROR            java.lang.Throwable -    ... 18 more
2016-10-24 09:14:31,848: 2157   [           main] ERROR            java.lang.Throwable - Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localPropertiesBean' defined in class path resource [rocks/inspectit/server/property/PropertyManager.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [protected synchronized java.util.Properties rocks.inspectit.server.property.PropertyManager.getProperties()] threw exception; nested exception is java.lang.NullPointerException
2016-10-24 09:14:31,848: 2157   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:603)
2016-10-24 09:14:31,849: 2158   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1057)
2016-10-24 09:14:31,849: 2158   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:953)
2016-10-24 09:14:31,849: 2158   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
2016-10-24 09:14:31,849: 2158   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
2016-10-24 09:14:31,849: 2158   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
2016-10-24 09:14:31,850: 2159   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
2016-10-24 09:14:31,850: 2159   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
2016-10-24 09:14:31,850: 2159   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
2016-10-24 09:14:31,850: 2159   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
2016-10-24 09:14:31,850: 2159   [           main] ERROR            java.lang.Throwable -    ... 36 more
2016-10-24 09:14:31,851: 2160   [           main] ERROR            java.lang.Throwable - Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [protected synchronized java.util.Properties rocks.inspectit.server.property.PropertyManager.getProperties()] threw exception; nested exception is java.lang.NullPointerException
2016-10-24 09:14:31,851: 2160   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:181)
2016-10-24 09:14:31,851: 2160   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:592)
2016-10-24 09:14:31,851: 2160   [           main] ERROR            java.lang.Throwable -    ... 45 more
2016-10-24 09:14:31,852: 2161   [           main] ERROR            java.lang.Throwable - Caused by: java.lang.NullPointerException
2016-10-24 09:14:31,852: 2161   [           main] ERROR            java.lang.Throwable -    at rocks.inspectit.server.property.PropertyManager.getProperties(PropertyManager.java:279)
2016-10-24 09:14:31,852: 2161   [           main] ERROR            java.lang.Throwable -    at rocks.inspectit.server.property.PropertyManager$$EnhancerBySpringCGLIB$$696b0f3.CGLIB$getProperties$0(<generated>)
2016-10-24 09:14:31,852: 2161   [           main] ERROR            java.lang.Throwable -    at rocks.inspectit.server.property.PropertyManager$$EnhancerBySpringCGLIB$$696b0f3$$FastClassBySpringCGLIB$$edd44050.invoke(<generated>)
2016-10-24 09:14:31,852: 2161   [           main] ERROR            java.lang.Throwable -    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
2016-10-24 09:14:31,853: 2162   [           main] ERROR            java.lang.Throwable -    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:292)
2016-10-24 09:14:31,853: 2162   [           main] ERROR            java.lang.Throwable -    at rocks.inspectit.server.property.PropertyManager$$EnhancerBySpringCGLIB$$696b0f3.getProperties(<generated>)
2016-10-24 09:14:31,853: 2162   [           main] ERROR            java.lang.Throwable -    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-10-24 09:14:31,853: 2162   [           main] ERROR            java.lang.Throwable -    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2016-10-24 09:14:31,853: 2162   [           main] ERROR            java.lang.Throwable -    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-10-24 09:14:31,853: 2162   [           main] ERROR            java.lang.Throwable -    at java.lang.reflect.Method.invoke(Method.java:606)
2016-10-24 09:14:31,854: 2163   [           main] ERROR            java.lang.Throwable -    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:160)
2016-10-24 09:14:31,854: 2163   [           main] ERROR            java.lang.Throwable -    ... 46 more
```

I've got the same problem with latest 1.7.3.86 version.

**Comment by ivansenic** [comment]
Hi @anthony-o,

Seams like default CMR configuration file can not be found by the container. The one should be available on the `[CMR_ROOT]/config/default.xml`. 

I am not sure if something is going wrong with the volumes assignment in the container start: 
`-v /var/local/inspectIT/config:/CMR/config -v /var/local/inspectIT/ci:/CMR/ci`.
 Can you please check that this is correct setup?

Still this should not result in the NPE error, but with a correct error message that default config file is missing. I will create a ticket for this and fix it right away.

**Comment by ivansenic** [comment]
https://inspectit-performance.atlassian.net/browse/INSPECTIT-2228

**Comment by ivansenic** [comment]
Fix for better message: https://github.com/inspectIT/inspectIT/pull/174

**Comment by anthony-o** [comment]
Here is a PR to fix this: inspectit-docker/cmr/pull/5

**Comment by matthias-huber** [comment]
Hi @anthony-o,

thanks for your Pull Request. We'll have a look at this issue and try to fix it latest next friday.

**Comment by matthias-huber** [comment]
@anthony-o I pushed your PR to the master branch. Changed the commit message. That's why I haven't used your PR directly.

Currently the fix is only available in the 'latest' image. Do you need it for the stable version?

**Comment by anthony-o** [comment]
No it's OK thank you.
